### ISSUE TITLE
add support for Java Event#from_json

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-gelf#36]
As done [in the json codec](https://github.com/logstash-plugins/logstash-codec-json/blob/fd0b6efbb851ece48a37466eb10eff69485dec35/lib/logstash/codecs/json.rb#L47-L83), we should add backward compatible support for using the upcoming `Event#from_json` method to speedup deserialization starting in 2.3.

**Comment by vervas** [comment]
Thanks for pointing this out. Will put it in pipeline for the next releases.

**Comment by vervas** [comment]
@colinsurprenant can we close this now?

**Comment by colinsurprenant** [comment]
yeah, I guess we can, this was fixed by #27
