### ISSUE TITLE
Gelfd failed to parse a message skipping

### ISSUE THREAD

**Issue by karthiklml** [logstash-plugins/logstash-input-gelf#4]
Hi,

I am enabling the GELF input in the logstash and pushing some json code for testing . 
Testing scenario is json test input => logstash-shipper => logstash => ES => UI . i am getting the following error . logstash version is 1.4.2

:message=>"Gelfd failed to parse a message skipping", :exception=>#, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:14:in parse'", "/opt/logstash/lib/logstash/inputs/gelf.rb:83:inudp_listener'", "/opt/logstash/lib/logstash/inputs/gelf.rb:60:in run'", "/opt/logstash/lib/logstash/pipeline.rb:163:ininputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}

Please suggest me what is the root cause of it . and how to fix it .

Thanks

**Comment by karthiklml** [comment]
Hi 

any updates in the above issue.

**Comment by untergeek** [comment]
Closing as GELF is a community plugin and being handled by others now.  Also, this bug dates back to 1.4.2, so it may not even be a bug any more.

If this is in error, feel free to re-open, or open a new ticket.
