### ISSUE TITLE
Add TCP support

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-input-gelf#6]
Graylog 0.10 starts supporting TCP transport for gelf.
Since this enables safer transport than UDP, I suggest extending the gelf input/output with a TCP option.

migrated from: https://logstash.jira.com/browse/LOGSTASH-780

**Comment by maxhyjal** [comment]
Is TCP option going to be supported anytime soon?

**Comment by daniilyar** [comment]
+1, this blocks me in propagating Icinga2 check results to Logstash via Icinga2 GELF plugin (because  Icinga2 GELF plugin can use tcp only).

**Comment by 0x736861** [comment]
+1

**Comment by maxhyjal** [comment]
Will this be supported anytime soon? UDP isn't really reliable if I want to collect metrics via gelf input

**Comment by maxhyjal** [comment]
@jordansissel not sure if I should @ you here but who would be the best person to talk to? or probably this is of lower priority and then we can fix it and request a merge?

**Comment by daniilyar** [comment]
We have updated Logstash input with TCP support recently. Let me post the working code here as a Gist: https://gist.github.com/daniilyar/758857675856ee2fdbef. We will make a PR when we will have a free time.

**Comment by maxhyjal** [comment]
Excellent @daniilyar !

**Comment by marcuslinke** [comment]
+1

**Comment by voidengineer** [comment]
+1

**Comment by mvallerie** [comment]
+1

**Comment by ArthurasJ** [comment]
+1

**Comment by fraenki** [comment]
@daniilyar Ping. Care to submit a PR? People are already using your code... so this would make sense, I guess.

**Comment by dracontb** [comment]
Do I need to install icinga for this code to work? Isn't gelf plugin packaged with logstash 2.2 already supporting TCP? If so, what configuration to make it work?

**Comment by JochenSzostek** [comment]
+1

**Comment by bombaju** [comment]
+1

**Comment by vingrad** [comment]
+1

**Comment by explicitcall** [comment]
+1

**Comment by shoutcool** [comment]
would be great to see tcp support coming to gelf plugin soon.

**Comment by Hermain** [comment]
+1

**Comment by pablolibo** [comment]
+1

**Comment by iFedix** [comment]
I don't understand.. is this supported in a sort of way or not? +1 in case not

**Comment by jordansissel** [comment]
I have deleted all of the "+1" comments. At the time of deletion, there were 12 `+1` comments.

**Comment by iFedix** [comment]
Hey guys! Based on @daniilyar files, i adapted his file to last logstash version (5.4). It's working but it's a porting from an old version of the plugin, so lot of things changed and maybe it isn't optimized.. Also I did not test the udp part of the script, because i needed only tcp (i need nxlog tcp gelf to connect to logstash). You can download the file here: [logstash-input-gelf-master.zip](https://github.com/logstash-plugins/logstash-input-gelf/files/1044729/logstash-input-gelf-master.zip). Maybe it's a good start to add this in the current logstash-input-gelf plugin! Hope this helps someone! 😄

**Comment by patricklucas** [comment]
Any update on this?

**Comment by iFedix** [comment]
@patricklucas this is my working updated version based on the last offical release: 
[logstash-input-gelf-master.zip](https://github.com/logstash-plugins/logstash-input-gelf/files/1107866/logstash-input-gelf-master.zip). It's working well!

**Comment by azman0101** [comment]
How to enable TCP ? Is this master is now released ?

**Comment by Hermain** [comment]
The docker gelf loging driver now supports tcp output. Logstash needs to be able to receive that. https://docs.docker.com/engine/admin/logging/gelf/#gelf-options

**Comment by omermizrahi** [comment]
Hi does this work for somone? i try to work with gelf tcp input but get this in logs:
[[main]<gelf] WARN logstash.inputs.gelf - Starting gelf listener (tcp)
and no logs are processing when sent to TCP.
im working in a logstash docker and installed the custom gelf-input.

**Comment by jsvd** [comment]
implemented in https://github.com/logstash-plugins/logstash-input-gelf/pull/59 and shipped already in version 3.1.0 to rubygems.org
